import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MuiThemeProvider from "@/providers/muiThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100`}
      >
        <MuiThemeProvider>
          <header className="border-b border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900">
            <div className="mx-auto max-w-4xl px-4 py-4">
              <nav className="flex items-center gap-6">
                <a href="/" className="font-semibold hover:underline">
                  Accueil
                </a>
                <a href="/ideas" className="font-semibold hover:underline">
                  Idées
                </a>
                <a href="/problems" className="font-semibold hover:underline ">
                  Problèmes
                </a>
                {/* <a href="/associations" className="font-semibold hover:underline">
                  Associations
                </a> */}
              </nav>
            </div>
          </header>
          <main className="flex-1 mx-auto w-full max-w-6xl px-4 py-8">
            {children}
          </main>
        </MuiThemeProvider>

        <footer className="border-t border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 mt-auto">
          <div className="mx-auto max-w-4xl px-4 py-4 text-sm text-zinc-500 dark:text-zinc-400" suppressHydrationWarning>
            my business ideas© {new Date().getFullYear()}
          </div>
        </footer>
      </body>
    </html>
  );
}
